FROM ubuntu:19.10
MAINTAINER liulucas
RUN  sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list

#RUN apk update && apk add openjdk8 
RUN apt-get update && apt-get install -y openjdk-8-jdk && \
	apt-get install unzip && \
	apt-get install sudo && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /var/cache/oracle-jdk8-installer

ARG PACKAGE_NAME="allure-commandline-2.13.5.zip"
ENV ALLURE_PATH=/allure-commandline
COPY ${PACKAGE_NAME} .
RUN mkdir -p "${ALLURE_PATH}" && \
	unzip "${PACKAGE_NAME}" -d "${ALLURE_PATH}" && \
	rm -Rf "${PACKAGE_NAME}"
ENV PATH=$PATH:$ALLURE_PATH/allure-commandline-2.13.5/bin
RUN sudo chmod +x /allure-commandline/allure-commandline-2.13.5/bin/*
CMD ["allure", "--version"]







	




























