version: "3"
services:
  myapp:
    image: selenium-python:v1
    volumes:
      - ./:/code  # 这里把刚刚的代码映射到这个目录
    command: python /code/docker_selenium_demo.py 
    depends_on:
       - chrome
            #condition: service_healthy
    links:
        - chrome
  chrome:
    image: selenium/standalone-chrome:3.4.0
    ports:
      - "4444:4444"
    shm_size: 2g
    healthcheck:
        test: ["CMD","curl", "-f", "http://localhost:4444/wd/hub"]
        interval: 30s
        timeout: 5s
        retries: 3
