# docker-compose.yml
version: '3.7'
services:
    mantisbt:
      image: xlrl/mantisbt:latest
      container_name: mantis
      volumes:
        - C:\diy\Dockerfiles\mantis\config:/var/www/html/config
      ports:
        - "8989:80"
      links:
        - mysql
      restart: always

    mysql:
      image: mysql:5.7
      container_name: mysql
      volumes:
        - C:\diy\Dockerfiles\mantis\data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=bugtracker
        - MYSQL_USER=mantisbt
        - MYSQL_PASSWORD=mantisbt
      restart: always