version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - 'C:\diy\Dockerfiles\testlink\db_data:/bitnami/mariadb'
  testlink:
    image: docker.io/bitnami/testlink:latest
    ports:
      - '83:8080'
      - '443:8443'
    environment:
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=123456
      - TESTLINK_LANGUAGE=zh_CN
      - TESTLINK_DATABASE_HOST=mariadb
      - TESTLINK_DATABASE_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'C:\diy\Dockerfiles\testlink\data:/bitnami/testlink'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local